-- MySQL Script generated by MySQL Workbench
-- Sun Dec 14 20:58:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kurumpersoneldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kurumpersoneldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kurumpersoneldb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_turkish_ci ;
USE `kurumpersoneldb` ;

-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`kurumbilgileri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`kurumbilgileri` (
  `KurumID`  NOT NULL,
  `KurumAdi` VARCHAR(150) NOT NULL,
  `Adres` VARCHAR(255) NULL DEFAULT NULL,
  `Telefon` VARCHAR(15) NULL DEFAULT NULL,
  `EPosta` VARCHAR(50) NULL DEFAULT NULL,
  `KepAdresi` VARCHAR(100) NULL DEFAULT NULL,
  `OlusturmaZamani`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`KurumID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`birimbilgileri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`birimbilgileri` (
  `BirimID`  NOT NULL,
  `KurumID`  NOT NULL,
  `UstBirimID`  NULL DEFAULT NULL,
  `BirimAdi` VARCHAR(150) NOT NULL,
  `OlusturmaZamani`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`BirimID`),
  INDEX `KurumID` (`KurumID` ASC) VISIBLE,
  INDEX `UstBirimID` (`UstBirimID` ASC) VISIBLE,
  CONSTRAINT `birimbilgileri_ibfk_1`
    FOREIGN KEY (`KurumID`)
    REFERENCES `kurumpersoneldb`.`kurumbilgileri` (`KurumID`),
  CONSTRAINT `birimbilgileri_ibfk_2`
    FOREIGN KEY (`UstBirimID`)
    REFERENCES `kurumpersoneldb`.`birimbilgileri` (`BirimID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`personelbilgileri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`personelbilgileri` (
  `PersonelID`  NOT NULL,
  `TCKimlikNo` CHAR(11) NOT NULL,
  `SicilNumarasi` VARCHAR(45) NULL DEFAULT NULL,
  `Ad` VARCHAR(100) NOT NULL,
  `Soyad` VARCHAR(100) NOT NULL,
  `DogumTarihi` DATE NULL DEFAULT NULL,
  `Unvan` VARCHAR(50) NULL DEFAULT NULL,
  `Brans` VARCHAR(50) NULL DEFAULT NULL,
  `IseGirisTarihi` DATE NULL DEFAULT NULL,
  `PersonelDurumu` ENUM('Aktif', 'Pasif', 'Izinli', 'Emekli') NULL DEFAULT 'Aktif',
  `Adres` VARCHAR(255) NULL DEFAULT NULL,
  `Telefon` VARCHAR(15) NULL DEFAULT NULL,
  `EPosta` VARCHAR(100) NULL DEFAULT NULL,
  `IstihdamSekli` VARCHAR(150) NULL DEFAULT NULL,
  `OlusturmaZamani`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PersonelID`),
  UNIQUE INDEX `TCKimlikNo` (`TCKimlikNo` ASC) VISIBLE,
  UNIQUE INDEX `SicilNumarasi` (`SicilNumarasi` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`egitimbilgileri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`egitimbilgileri` (
  `EgitimID`  NOT NULL,
  `PersonelID`  NOT NULL,
  `TahsilTuru` ENUM('Lise', 'Ön Lisans', 'Lisans', 'Yüksek Lisans', 'Doktora') NULL DEFAULT NULL,
  `LiseAdi` VARCHAR(200) NULL DEFAULT NULL,
  `UniversiteAdi` VARCHAR(200) NULL DEFAULT NULL,
  `FakulteAdi` VARCHAR(150) NULL DEFAULT NULL,
  `BolumAdi` VARCHAR(150) NULL DEFAULT NULL,
  `DiplomaNo` VARCHAR(50) NULL DEFAULT NULL,
  `MezuniyetTarihi` DATE NULL DEFAULT NULL,
  `OlusturmaZamani`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`EgitimID`),
  INDEX `PersonelID` (`PersonelID` ASC) VISIBLE,
  CONSTRAINT `egitimbilgileri_ibfk_1`
    FOREIGN KEY (`PersonelID`)
    REFERENCES `kurumpersoneldb`.`personelbilgileri` (`PersonelID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`gorevtanimlari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`gorevtanimlari` (
  `GorevTanimID`  NOT NULL,
  `GorevAdi` VARCHAR(100) NOT NULL,
  `GorevKodu` VARCHAR(50) NULL DEFAULT NULL,
  `Aciklama` VARCHAR(255) NULL DEFAULT NULL,
  `OlusturmaZamani`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`GorevTanimID`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`kullanici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`kullanici` (
  `KullaniciID`  NOT NULL,
  `PersonelID`  NULL DEFAULT NULL,
  `KullaniciAdi` VARCHAR(50) NOT NULL,
  `SifreHash` VARCHAR(255) NOT NULL,
  `Aktif` (1) NULL DEFAULT '1',
  `OlusturmaZamani`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`KullaniciID`),
  UNIQUE INDEX `KullaniciAdi` (`KullaniciAdi` ASC) VISIBLE,
  INDEX `PersonelID` (`PersonelID` ASC) VISIBLE,
  CONSTRAINT `kullanici_ibfk_1`
    FOREIGN KEY (`PersonelID`)
    REFERENCES `kurumpersoneldb`.`personelbilgileri` (`PersonelID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`rol` (
  `RolID`  NOT NULL,
  `RolAdi` VARCHAR(50) NOT NULL,
  `Aciklama` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`RolID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`kullanicirolleri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`kullanicirolleri` (
  `KullaniciRolID`  NOT NULL,
  `KullaniciID`  NOT NULL,
  `RolID`  NOT NULL,
  `VerilisTarihi`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`KullaniciRolID`),
  INDEX `KullaniciID` (`KullaniciID` ASC) VISIBLE,
  INDEX `RolID` (`RolID` ASC) VISIBLE,
  CONSTRAINT `kullanicirolleri_ibfk_1`
    FOREIGN KEY (`KullaniciID`)
    REFERENCES `kurumpersoneldb`.`kullanici` (`KullaniciID`),
  CONSTRAINT `kullanicirolleri_ibfk_2`
    FOREIGN KEY (`RolID`)
    REFERENCES `kurumpersoneldb`.`rol` (`RolID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`personelgorevhareketleri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`personelgorevhareketleri` (
  `HareketID`  NOT NULL,
  `PersonelID`  NOT NULL,
  `BirimID`  NOT NULL,
  `GorevTanimID`  NOT NULL,
  `BaslangicTarihi` DATE NOT NULL,
  `BitisTarihi` DATE NULL DEFAULT NULL,
  `AktifGorevMi` (1) NULL DEFAULT '1',
  `OlusturmaZamani`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`HareketID`),
  INDEX `PersonelID` (`PersonelID` ASC) VISIBLE,
  INDEX `BirimID` (`BirimID` ASC) VISIBLE,
  INDEX `GorevTanimID` (`GorevTanimID` ASC) VISIBLE,
  CONSTRAINT `personelgorevhareketleri_ibfk_1`
    FOREIGN KEY (`PersonelID`)
    REFERENCES `kurumpersoneldb`.`personelbilgileri` (`PersonelID`),
  CONSTRAINT `personelgorevhareketleri_ibfk_2`
    FOREIGN KEY (`BirimID`)
    REFERENCES `kurumpersoneldb`.`birimbilgileri` (`BirimID`),
  CONSTRAINT `personelgorevhareketleri_ibfk_3`
    FOREIGN KEY (`GorevTanimID`)
    REFERENCES `kurumpersoneldb`.`gorevtanimlari` (`GorevTanimID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;


-- -----------------------------------------------------
-- Table `kurumpersoneldb`.`sistemloglari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurumpersoneldb`.`sistemloglari` (
  `LogID`  NOT NULL,
  `TabloAdi` VARCHAR(50) NULL DEFAULT NULL,
  `IslemTuru` VARCHAR(20) NULL DEFAULT NULL,
  `KayitID`  NULL DEFAULT NULL,
  `Aciklama` TEXT NULL DEFAULT NULL,
  `IslemYapan` VARCHAR(100) NULL DEFAULT NULL,
  `IslemTarihi`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LogID`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_turkish_ci;

USE `kurumpersoneldb` ;

-- -----------------------------------------------------
-- function fn_EmailOlustur
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `fn_EmailOlustur`(p_Ad VARCHAR(50), p_Soyad VARCHAR(50)) RETURNS varchar(150) CHARSET utf8mb4 COLLATE utf8mb4_turkish_ci
    DETERMINISTIC
BEGIN
    DECLARE temizAd VARCHAR(50);
    DECLARE temizSoyad VARCHAR(50);

    -- Adı küçük harfe çevir
    SET temizAd = LOWER(p_Ad);
    SET temizSoyad = LOWER(p_Soyad);

    -- Basit Türkçe karakter dönüşümleri (Örnek olarak en sık kullanılanlar)
    SET temizAd = REPLACE(temizAd, 'ş', 's');
    SET temizAd = REPLACE(temizAd, 'ü', 'u');
    SET temizAd = REPLACE(temizAd, 'ö', 'o');
    SET temizAd = REPLACE(temizAd, 'ç', 'c');
    SET temizAd = REPLACE(temizAd, 'ğ', 'g');
    SET temizAd = REPLACE(temizAd, 'ı', 'i');

    SET temizSoyad = REPLACE(temizSoyad, 'ş', 's');
    SET temizSoyad = REPLACE(temizSoyad, 'ü', 'u');
    SET temizSoyad = REPLACE(temizSoyad, 'ö', 'o');
    SET temizSoyad = REPLACE(temizSoyad, 'ç', 'c');
    SET temizSoyad = REPLACE(temizSoyad, 'ğ', 'g');
    SET temizSoyad = REPLACE(temizSoyad, 'ı', 'i');

    -- Format: ad.soyad@kurum.edu.tr
    RETURN CONCAT(temizAd, '.', temizSoyad, '@kurum.edu.tr');
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function fn_HizmetYiliHesapla
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `fn_HizmetYiliHesapla`(p_IseGirisTarihi DATE) RETURNS int
    DETERMINISTIC
BEGIN
    DECLARE yilFarki INT;
    IF p_IseGirisTarihi IS NULL THEN RETURN 0; END IF;
    SET yilFarki = TIMESTAMPDIFF(YEAR, p_IseGirisTarihi, CURDATE());
    RETURN yilFarki;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function fn_TCKNMaskele
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `fn_TCKNMaskele`(p_TCKN CHAR(11)) RETURNS varchar(11) CHARSET utf8mb4 COLLATE utf8mb4_turkish_ci
    DETERMINISTIC
BEGIN
    -- Eğer TCKN boşsa veya 11 hane değilse direkt geri döndür
    IF LENGTH(p_TCKN) != 11 THEN
        RETURN p_TCKN;
    END IF;

    -- İlk 2 hane + 7 yıldız + Son 2 hane
    RETURN CONCAT(LEFT(p_TCKN, 2), '*******', RIGHT(p_TCKN, 2));
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_BirimEkle
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_BirimEkle`(
    IN p_KurumID INT,          -- Hangi kuruma bağlı?
    IN p_UstBirimID INT,       -- Üst Birim ID (Yoksa NULL veya 0 gönderilebilir)
    IN p_BirimAdi VARCHAR(150),
    OUT p_Sonuc VARCHAR(255)
)
BEGIN
    -- Değişken tanımları
    DECLARE v_UstBirimVarMi INT DEFAULT 0;

    -- Hata yakalama
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_Sonuc = 'HATA: SQL işlem hatası oluştu. (Foreign Key kısıtlamasına takılmış olabilirsiniz)';
    END;

    START TRANSACTION;

    -- 1. ADIM: Üst Birim ID kontrolü (0 veya boş gelirse NULL yapalım)
    -- Veritabanında Foreign Key muhtemelen NULL değerini kabul ediyordur.
    IF p_UstBirimID = 0 OR p_UstBirimID = '' THEN
        SET p_UstBirimID = NULL;
    END IF;

    -- 2. ADIM: Mantıksal Kontroller
    -- A. Kurum var mı?
    IF NOT EXISTS (SELECT 1 FROM KurumBilgileri WHERE KurumID = p_KurumID) THEN
        SET p_Sonuc = 'HATA: Girilen Kurum ID bulunamadı.';
        ROLLBACK;
        
    -- B. Eğer Üst Birim girilmişse, o ID gerçekten var mı?
    ELSEIF p_UstBirimID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM BirimBilgileri WHERE BirimID = p_UstBirimID) THEN
        SET p_Sonuc = 'HATA: Girilen Üst Birim ID sistemde bulunamadı.';
        ROLLBACK;

    -- C. Aynı Üst Birim altında, aynı isimde birim var mı? (Çift kayıt önleme)
    -- IFNULL kullanımı: Üst birim NULL ise NULL olanları, doluysa o ID'yi kontrol eder.
    ELSEIF EXISTS (SELECT 1 FROM BirimBilgileri 
                   WHERE BirimAdi = p_BirimAdi 
                   AND KurumID = p_KurumID 
                   AND IFNULL(UstBirimID, 0) = IFNULL(p_UstBirimID, 0)) THEN
        SET p_Sonuc = CONCAT('HATA: ', p_BirimAdi, ' bu üst birim altında zaten kayıtlı.');
        ROLLBACK;

    ELSE
        -- 3. ADIM: Kayıt Ekleme
        INSERT INTO BirimBilgileri (KurumID, UstBirimID, BirimAdi)
        VALUES (p_KurumID, p_UstBirimID, p_BirimAdi);

        COMMIT;
        SET p_Sonuc = CONCAT('BAŞARILI: ', p_BirimAdi, ' eklendi.');
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_EgitimEkle
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_EgitimEkle`(
    IN p_PersonelID INT,
    IN p_TahsilTuru VARCHAR(50), -- 'Lise', 'Ön Lisans', 'Lisans', 'Yüksek Lisans', 'Doktora'
    IN p_LiseAdi VARCHAR(200),   -- Lise ise doldurulur, Üniversite ise NULL geçilir
    IN p_UniversiteAdi VARCHAR(200), -- Üniversite ise doldurulur
    IN p_FakulteAdi VARCHAR(150),
    IN p_BolumAdi VARCHAR(150),
    IN p_DiplomaNo VARCHAR(50),
    IN p_MezuniyetTarihi DATE,
    OUT p_Sonuc VARCHAR(255)
)
BEGIN
    -- Hata Yakalama (Transaction Rollback)
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_Sonuc = 'HATA: SQL işlem hatası oluştu.';
    END;

    START TRANSACTION;

    -- 1. KONTROL: Böyle bir personel var mı?
    -- (PersonelBilgileri tablosu olduğunu varsayıyoruz)
    IF NOT EXISTS (SELECT 1 FROM PersonelBilgileri WHERE PersonelID = p_PersonelID) THEN
        SET p_Sonuc = 'HATA: Belirtilen ID ile personel bulunamadı.';
        ROLLBACK;

    -- 2. KONTROL: Aynı Diploma Numarası zaten kayıtlı mı?
    ELSEIF EXISTS (SELECT 1 FROM egitimbilgileri WHERE DiplomaNo = p_DiplomaNo) THEN
        SET p_Sonuc = CONCAT('HATA: ', p_DiplomaNo, ' numaralı diploma zaten sistemde kayıtlı.');
        ROLLBACK;

    -- 3. KONTROL: Aynı kişi, aynı bölümü tekrar eklemeye çalışıyor mu?
    ELSEIF EXISTS (SELECT 1 FROM egitimbilgileri 
                   WHERE PersonelID = p_PersonelID 
                   AND TahsilTuru = p_TahsilTuru 
                   AND IFNULL(BolumAdi, '') = IFNULL(p_BolumAdi, '')) THEN
        SET p_Sonuc = 'HATA: Bu personel için bu eğitim bilgisi zaten mevcut.';
        ROLLBACK;

    ELSE
        -- 4. KAYIT İŞLEMİ
        INSERT INTO egitimbilgileri (
            PersonelID, 
            TahsilTuru, 
            LiseAdi, 
            UniversiteAdi, 
            FakulteAdi, 
            BolumAdi, 
            DiplomaNo, 
            MezuniyetTarihi, 
            OlusturmaZamani
        )
        VALUES (
            p_PersonelID, 
            p_TahsilTuru, 
            p_LiseAdi, 
            p_UniversiteAdi, 
            p_FakulteAdi, 
            p_BolumAdi, 
            p_DiplomaNo, 
            p_MezuniyetTarihi, 
            NOW() -- Şu anki zaman
        );

        COMMIT;
        SET p_Sonuc = 'BAŞARILI: Eğitim bilgisi eklendi.';
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_GorevTanimEkle
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GorevTanimEkle`(
    IN p_GorevAdi VARCHAR(100),
    IN p_GorevKodu VARCHAR(50), -- Benzersiz olması gereken kod (Örn: YZL-001)
    IN p_Aciklama VARCHAR(255), -- Zorunlu değilse boş gönderilebilir
    OUT p_Sonuc VARCHAR(255)
)
BEGIN
    -- Hata Yakalama Bloğu
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_Sonuc = 'HATA: SQL işlem hatası oluştu.';
    END;

    START TRANSACTION;

    -- 1. KONTROL: Aynı Görev Kodu ile kayıt var mı?
    IF EXISTS (SELECT 1 FROM gorevtanimlari WHERE GorevKodu = p_GorevKodu) THEN
        SET p_Sonuc = CONCAT('HATA: ', p_GorevKodu, ' kodu ile tanımlı bir görev zaten mevcut.');
        ROLLBACK;
        
    -- 2. KONTROL: Aynı Görev Adı ile kayıt var mı? (İsteğe bağlı ama önerilir)
    ELSEIF EXISTS (SELECT 1 FROM gorevtanimlari WHERE GorevAdi = p_GorevAdi) THEN
        SET p_Sonuc = CONCAT('HATA: ', p_GorevAdi, ' isminde bir görev tanımı zaten yapılmış.');
        ROLLBACK;

    ELSE
        -- 3. KAYIT İŞLEMİ
        INSERT INTO gorevtanimlari (
            GorevAdi, 
            GorevKodu, 
            Aciklama, 
            OlusturmaZamani
        ) 
        VALUES (
            p_GorevAdi, 
            p_GorevKodu, 
            p_Aciklama, 
            NOW() -- Şu anki tarih ve saati otomatik basar
        );
        
        COMMIT;
        SET p_Sonuc = CONCAT('BAŞARILI: ', p_GorevAdi, ' görevi tanımlandı.');
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_KullaniciOlustur
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_KullaniciOlustur`(
    IN p_PersonelID INT,
    IN p_KullaniciAdi VARCHAR(50),
    IN p_Sifre VARCHAR(255),
    OUT p_Sonuc VARCHAR(255)
)
BEGIN
    -- 1. Personel var mı?
    IF NOT EXISTS (SELECT 1 FROM PersonelBilgileri WHERE PersonelID = p_PersonelID) THEN
        SET p_Sonuc = 'HATA: Belirtilen ID ile personel bulunamadı.';
        
    -- 2. Kullanıcı adı dolu mu? (Unique constraint hatası almamak için ön kontrol)
    ELSEIF EXISTS (SELECT 1 FROM Kullanici WHERE KullaniciAdi = p_KullaniciAdi) THEN
        SET p_Sonuc = 'HATA: Bu kullanıcı adı zaten kullanılıyor.';
        
    -- 3. Bu personelin zaten bir kullanıcısı var mı?
    ELSEIF EXISTS (SELECT 1 FROM Kullanici WHERE PersonelID = p_PersonelID) THEN
        SET p_Sonuc = 'HATA: Bu personelin zaten bir kullanıcı hesabı var.';
        
    ELSE
        INSERT INTO Kullanici (PersonelID, KullaniciAdi, SifreHash) 
        VALUES (p_PersonelID, p_KullaniciAdi, p_Sifre); -- Normalde burada SHA2(p_Sifre, 256) kullanılır.
        
        SET p_Sonuc = CONCAT('BAŞARILI: ', p_KullaniciAdi, ' kullanıcısı oluşturuldu.');
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_KullaniciRolAta
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_KullaniciRolAta`(
    IN p_KullaniciID INT,
    IN p_RolID INT,
    OUT p_Sonuc VARCHAR(255)
)
BEGIN
    -- Kullanıcı ve Rol var mı kontrolü
    IF NOT EXISTS (SELECT 1 FROM Kullanici WHERE KullaniciID = p_KullaniciID) THEN
        SET p_Sonuc = 'HATA: Kullanıcı bulunamadı.';
    ELSEIF NOT EXISTS (SELECT 1 FROM Rol WHERE RolID = p_RolID) THEN
        SET p_Sonuc = 'HATA: Rol bulunamadı.';
        
    -- Zaten bu role sahip mi?
    ELSEIF EXISTS (SELECT 1 FROM KullaniciRolleri WHERE KullaniciID = p_KullaniciID AND RolID = p_RolID) THEN
        SET p_Sonuc = 'UYARI: Kullanıcı zaten bu role sahip.';
        
    ELSE
        INSERT INTO KullaniciRolleri (KullaniciID, RolID) VALUES (p_KullaniciID, p_RolID);
        SET p_Sonuc = 'BAŞARILI: Rol ataması yapıldı.';
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_KurumEkle
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_KurumEkle`(
    IN p_KurumAdi VARCHAR(150),
    IN p_Adres VARCHAR(255),
    IN p_Telefon VARCHAR(15),
    IN p_EPosta VARCHAR(50),
    IN p_KepAdresi VARCHAR(100),
    OUT p_Sonuc VARCHAR(255)
)
BEGIN
    -- Beklenmedik bir SQL hatası olursa (Örn: Veri tipi uyumsuzluğu) işlemi geri al
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_Sonuc = 'HATA: Beklenmedik bir SQL hatası oluştu. Kayıt yapılamadı.';
    END;

    START TRANSACTION;

    -- 1. Bu isimde bir kurum zaten var mı? (Çift kayıt kontrolü)
    IF EXISTS (SELECT 1 FROM KurumBilgileri WHERE KurumAdi = p_KurumAdi) THEN
        SET p_Sonuc = CONCAT('UYARI: ', p_KurumAdi, ' isimli kurum zaten sistemde mevcut.');
        ROLLBACK; -- Değişiklik yapmadan çık
    ELSE
        -- 2. Kayıt Ekleme İşlemi
        -- Not: Tablo sütun isimlerinin parametrelerle örtüştüğünü varsayıyorum.
        INSERT INTO KurumBilgileri (KurumAdi, Adres, Telefon, EPosta, KepAdresi) 
        VALUES (p_KurumAdi, p_Adres, p_Telefon, p_EPosta, p_KepAdresi);
        
        COMMIT; -- İşlemi onayla
        SET p_Sonuc = CONCAT('BAŞARILI: ', p_KurumAdi, ' sisteme eklendi.');
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_PersonelDetayliListesiGetir
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_PersonelDetayliListesiGetir`()
BEGIN
    SELECT 
        p.TCKimlikNo,
        p.Ad,
        p.Soyad,
        p.PersonelDurumu,
        b.BirimAdi,
        g.GorevAdi,
        h.BaslangicTarihi
    FROM PersonelBilgileri p
    LEFT JOIN PersonelGorevHareketleri h ON p.PersonelID = h.PersonelID AND h.AktifGorevMi = 1
    LEFT JOIN BirimBilgileri b ON h.BirimID = b.BirimID
    LEFT JOIN GorevTanimlari g ON h.GorevTanimID = g.GorevTanimID
    ORDER BY p.Ad, p.Soyad;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_PersonelIletisimGuncelle
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_PersonelIletisimGuncelle`(
    IN p_TCKimlikNo CHAR(11),
    IN p_YeniTelefon VARCHAR(15),
    IN p_YeniAdres VARCHAR(255),
    IN p_YeniEposta VARCHAR(100)
)
BEGIN
    -- Güncelleme işlemi
    UPDATE PersonelBilgileri
    SET 
        Telefon = p_YeniTelefon,
        Adres = p_YeniAdres,
        EPosta = p_YeniEposta
    WHERE TCKimlikNo = p_TCKimlikNo;
    
    SELECT 'BAŞARILI: İletişim bilgileri güncellendi.' AS Mesaj;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_PersonelIseAlim
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_PersonelIseAlim`(
            IN p_TCKimlikNo CHAR(11),
            IN p_Ad VARCHAR(100),
            IN p_Soyad VARCHAR(100),
            IN p_SicilNumarasi VARCHAR(45),
            IN p_DogumTarihi DATE,
            IN p_Unvan VARCHAR(50),
            IN p_Brans VARCHAR(50),
            IN p_Adres VARCHAR(255),
            IN p_Telefon VARCHAR(15),
            IN p_EPosta VARCHAR(100),
            IN p_IstihdamSekli VARCHAR(150),
            IN p_BirimID INT,
            IN p_GorevTanimID INT,
            IN p_IseGirisTarihi DATE,
            OUT p_SonucMesaji VARCHAR(255)
        )
BEGIN
            DECLARE EXIT HANDLER FOR SQLEXCEPTION
            BEGIN
                ROLLBACK;
                SET p_SonucMesaji = 'HATA: Veritabanı kaydı yapılamadı (TC veya Veri Hatası).';
            END;

            START TRANSACTION;

            INSERT INTO PersonelBilgileri (
                TCKimlikNo, Ad, Soyad, SicilNumarasi, DogumTarihi, 
                Unvan, Brans, Adres, Telefon, EPosta, 
                IstihdamSekli, IseGirisTarihi, PersonelDurumu
            )
            VALUES (
                p_TCKimlikNo, p_Ad, p_Soyad, p_SicilNumarasi, p_DogumTarihi,
                p_Unvan, p_Brans, p_Adres, p_Telefon, p_EPosta,
                p_IstihdamSekli, p_IseGirisTarihi, 'Aktif'
            );

            SET @YeniID = LAST_INSERT_ID();

            INSERT INTO PersonelGorevHareketleri (
                PersonelID, BirimID, GorevTanimID, BaslangicTarihi, AktifGorevMi
            )
            VALUES (
                @YeniID, p_BirimID, p_GorevTanimID, p_IseGirisTarihi, 1
            );

            COMMIT;
            SET p_SonucMesaji = 'BAŞARILI: Personel kaydı tamamlandı.';
        END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_PersonelKaydiSil
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_PersonelKaydiSil`(
    IN p_TCKimlikNo CHAR(11)
)
BEGIN
    -- Personeli tamamen silmek yerine 'Pasif'e çekiyoruz (Soft Delete)
    -- Ayrıca görev hareketini sonlandırıyoruz.
    DECLARE v_PersonelID INT;
    
    SELECT PersonelID INTO v_PersonelID FROM PersonelBilgileri WHERE TCKimlikNo = p_TCKimlikNo;

    IF v_PersonelID IS NOT NULL THEN
        -- 1. Personel Durumunu Pasif Yap
        UPDATE PersonelBilgileri SET PersonelDurumu = 'Pasif' WHERE PersonelID = v_PersonelID;
        
        -- 2. Aktif görevini sonlandır (Bugünün tarihiyle bitir)
        UPDATE PersonelGorevHareketleri 
        SET BitisTarihi = CURDATE(), AktifGorevMi = 0 
        WHERE PersonelID = v_PersonelID AND AktifGorevMi = 1;
        
        SELECT 'BAŞARILI: Personel kaydı pasife alındı ve ilişkisi kesildi.' AS Mesaj;
    ELSE
        SELECT 'HATA: Personel bulunamadı.' AS Mesaj;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_PersonelSilGuvenli
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_PersonelSilGuvenli`(
    IN p_PersonelID INT,
    OUT p_Sonuc VARCHAR(255)
)
BEGIN
    -- Hata yakalama
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_Sonuc = 'HATA: Silme işlemi sırasında bir sorun oluştu.';
    END;

    START TRANSACTION;

    -- 1. ADIM: Personel var mı kontrol et
    IF NOT EXISTS (SELECT 1 FROM PersonelBilgileri WHERE PersonelID = p_PersonelID) THEN
        SET p_Sonuc = 'HATA: Silinecek personel bulunamadı.';
        ROLLBACK;
    ELSE
        -- 2. ADIM: ÖNCE BAĞLI (ÇOCUK) TABLOLARI TEMİZLE
        -- Hata veren tablo burasıydı:
        DELETE FROM PersonelGorevHareketleri WHERE PersonelID = p_PersonelID;
        
        -- Eğer Eğitim Bilgileri tablosu varsa onu da temizlemeliyiz:
        DELETE FROM egitimbilgileri WHERE PersonelID = p_PersonelID;

        -- (Varsa Maaş, İzin vb. diğer tablolar da buraya eklenmeli)

        -- 3. ADIM: ARTIK PERSONELİN KENDİSİNİ SİLEBİLİRİZ
        DELETE FROM PersonelBilgileri WHERE PersonelID = p_PersonelID;
        
        COMMIT;
        SET p_Sonuc = CONCAT('BAŞARILI: ', p_PersonelID, ' ID numaralı personel ve tüm geçmişi silindi.');
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_RolEkle
-- -----------------------------------------------------

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_RolEkle`(
    IN p_RolAdi VARCHAR(50),
    IN p_Aciklama VARCHAR(255),
    OUT p_Sonuc VARCHAR(255)
)
BEGIN
    IF EXISTS (SELECT 1 FROM Rol WHERE RolAdi = p_RolAdi) THEN
        SET p_Sonuc = 'HATA: Bu rol zaten tanımlı.';
    ELSE
        INSERT INTO Rol (RolAdi, Aciklama) VALUES (p_RolAdi, p_Aciklama);
        SET p_Sonuc = CONCAT('BAŞARILI: ', p_RolAdi, ' rolü eklendi.');
    END IF;
END$$

DELIMITER ;
USE `kurumpersoneldb`;

DELIMITER $$
USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Kurum_Delete`
AFTER DELETE ON `kurumpersoneldb`.`kurumbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('KurumBilgileri', 'SİLME', OLD.KurumID, CONCAT(OLD.KurumAdi, ' silindi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Kurum_Insert`
AFTER INSERT ON `kurumpersoneldb`.`kurumbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('KurumBilgileri', 'EKLEME', NEW.KurumID, CONCAT(NEW.KurumAdi, ' eklendi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Kurum_Update`
AFTER UPDATE ON `kurumpersoneldb`.`kurumbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('KurumBilgileri', 'GÜNCELLEME', NEW.KurumID, CONCAT('Kurum adı değişti: ', OLD.KurumAdi, ' -> ', NEW.KurumAdi), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Birim_Delete`
AFTER DELETE ON `kurumpersoneldb`.`birimbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('BirimBilgileri', 'SİLME', OLD.BirimID, CONCAT(OLD.BirimAdi, ' birimi silindi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Birim_Insert`
AFTER INSERT ON `kurumpersoneldb`.`birimbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('BirimBilgileri', 'EKLEME', NEW.BirimID, CONCAT(NEW.BirimAdi, ' birimi eklendi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Birim_Update`
AFTER UPDATE ON `kurumpersoneldb`.`birimbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('BirimBilgileri', 'GÜNCELLEME', NEW.BirimID, CONCAT('Birim adı değişti: ', OLD.BirimAdi, ' -> ', NEW.BirimAdi), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Personel_Delete`
AFTER DELETE ON `kurumpersoneldb`.`personelbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('PersonelBilgileri', 'SİLME', OLD.PersonelID, CONCAT(OLD.Ad, ' ', OLD.Soyad, ' silindi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Personel_Insert`
AFTER INSERT ON `kurumpersoneldb`.`personelbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('PersonelBilgileri', 'EKLEME', NEW.PersonelID, CONCAT(NEW.Ad, ' ', NEW.Soyad, ' eklendi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Personel_Update`
AFTER UPDATE ON `kurumpersoneldb`.`personelbilgileri`
FOR EACH ROW
BEGIN
    DECLARE degisiklik TEXT;
    SET degisiklik = CONCAT('Personel Güncellendi. ',
        IF(OLD.Ad != NEW.Ad, CONCAT('Ad: ', OLD.Ad, ' -> ', NEW.Ad, '. '), ''),
        IF(OLD.Soyad != NEW.Soyad, CONCAT('Soyad: ', OLD.Soyad, ' -> ', NEW.Soyad, '. '), ''),
        IF(OLD.Unvan != NEW.Unvan, CONCAT('Unvan: ', OLD.Unvan, ' -> ', NEW.Unvan, '. '), ''),
        IF(OLD.PersonelDurumu != NEW.PersonelDurumu, CONCAT('Durum: ', OLD.PersonelDurumu, ' -> ', NEW.PersonelDurumu), '')
    );
    
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('PersonelBilgileri', 'GÜNCELLEME', NEW.PersonelID, degisiklik, USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Egitim_Delete`
AFTER DELETE ON `kurumpersoneldb`.`egitimbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('egitimbilgileri', 'SİLME', OLD.EgitimID, CONCAT('PersonelID: ', OLD.PersonelID, ' ait eğitim kaydı silindi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Egitim_Insert`
AFTER INSERT ON `kurumpersoneldb`.`egitimbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('egitimbilgileri', 'EKLEME', NEW.EgitimID, CONCAT('PersonelID: ', NEW.PersonelID, ' için ', IFNULL(NEW.UniversiteAdi, NEW.LiseAdi), ' eklendi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Egitim_Update`
AFTER UPDATE ON `kurumpersoneldb`.`egitimbilgileri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('egitimbilgileri', 'GÜNCELLEME', NEW.EgitimID, CONCAT('Eğitim bilgisi güncellendi. Eski: ', IFNULL(OLD.UniversiteAdi, OLD.LiseAdi), ' Yeni: ', IFNULL(NEW.UniversiteAdi, NEW.LiseAdi)), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Gorev_Delete`
AFTER DELETE ON `kurumpersoneldb`.`gorevtanimlari`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('gorevtanimlari', 'SİLME', OLD.GorevTanimID, CONCAT(OLD.GorevAdi, ' görevi silindi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Gorev_Insert`
AFTER INSERT ON `kurumpersoneldb`.`gorevtanimlari`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('gorevtanimlari', 'EKLEME', NEW.GorevTanimID, CONCAT(NEW.GorevAdi, ' (', NEW.GorevKodu, ') eklendi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Gorev_Update`
AFTER UPDATE ON `kurumpersoneldb`.`gorevtanimlari`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('gorevtanimlari', 'GÜNCELLEME', NEW.GorevTanimID, CONCAT('Görev güncellendi. Eski: ', OLD.GorevAdi, ' -> Yeni: ', NEW.GorevAdi), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Kullanici_Log`
AFTER INSERT ON `kurumpersoneldb`.`kullanici`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('Kullanicilar', 'EKLEME', NEW.KullaniciID, CONCAT('Kullanıcı: ', NEW.KullaniciAdi, ' (PersonelID: ', NEW.PersonelID, ')'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Rol_Log`
AFTER INSERT ON `kurumpersoneldb`.`rol`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('Roller', 'EKLEME', NEW.RolID, CONCAT('Yeni Rol: ', NEW.RolAdi), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_Yetki_Log`
AFTER INSERT ON `kurumpersoneldb`.`kullanicirolleri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES ('KullaniciRolleri', 'YETKİLENDİRME', NEW.KullaniciRolID, CONCAT('KullaniciID: ', NEW.KullaniciID, ' -> RolID: ', NEW.RolID, ' yetkisi verildi.'), USER());
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_GorevHareket_Delete`
AFTER DELETE ON `kurumpersoneldb`.`personelgorevhareketleri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES (
        'PersonelGorevHareketleri', 
        'SİLME', 
        OLD.HareketID, 
        CONCAT('PersonelID: ', OLD.PersonelID, ' ye ait görev kaydı (ID: ', OLD.HareketID, ') silindi.'), 
        USER()
    );
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_GorevHareket_Insert`
AFTER INSERT ON `kurumpersoneldb`.`personelgorevhareketleri`
FOR EACH ROW
BEGIN
    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES (
        'PersonelGorevHareketleri', 
        'EKLEME', 
        NEW.HareketID, -- Tablondaki Primary Key (Varsa)
        CONCAT('PersonelID: ', NEW.PersonelID, ' için yeni görev ataması yapıldı. (BirimID: ', NEW.BirimID, ', GörevID: ', NEW.GorevTanimID, ')'), 
        USER()
    );
END$$

USE `kurumpersoneldb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `kurumpersoneldb`.`trg_GorevHareket_Update`
AFTER UPDATE ON `kurumpersoneldb`.`personelgorevhareketleri`
FOR EACH ROW
BEGIN
    DECLARE detay VARCHAR(255);
    
    -- Aktiflik durumu değiştiyse belirtelim
    IF OLD.AktifGorevMi != NEW.AktifGorevMi THEN
        SET detay = CONCAT('Görev statüsü değişti (Eski: ', OLD.AktifGorevMi, ' -> Yeni: ', NEW.AktifGorevMi, '). ');
    ELSE
        SET detay = 'Görev detayları güncellendi. ';
    END IF;

    INSERT INTO SistemLoglari (TabloAdi, IslemTuru, KayitID, Aciklama, IslemYapan)
    VALUES (
        'PersonelGorevHareketleri', 
        'GÜNCELLEME', 
        NEW.HareketID, 
        CONCAT('PersonelID: ', NEW.PersonelID, ' - ', detay), 
        USER()
    );
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
